import Reactive from "reactive-js";

export default () => {
  return (
    <div>
      <h1>Welcome to your Reactive App!</h1>
      <p>This app was generated by <code>create-reactive-app</code>.</p>
    </div>
  );
};
